const REGISTER_NEW_STUDENT = 'REGISTER_NEW_STUDENT';
const GET_USERS_PROFILE = 'GET_USERS_PROFILE';
const ADD_NEW_QUEST = 'ADD_NEW_QUEST';
const GET_ALL_QUESTION_ANSWERS = 'GET_ALL_QUESTION_ANSWERS';
const UPDATE_QUESTION_ANSWER = 'UPDATE_QUESTION_ANSWER';
const CHECK_NEW_STUDENT = 'CHECK_NEW_STUDENT';
const UPDATE_STUDENT = 'UPDATE_STUDENT';

const IS_AUTH = 'IS_AUTH';

export {
  REGISTER_NEW_STUDENT,
  ADD_NEW_QUEST,
  GET_ALL_QUESTION_ANSWERS,
  UPDATE_QUESTION_ANSWER,
  CHECK_NEW_STUDENT,
  IS_AUTH,
  GET_USERS_PROFILE,
  UPDATE_STUDENT,
};
