const REGISTER_NEW_STUDENT = 'REGISTER_NEW_STUDENT';
const GET_ALL_QUESTION_ANSWERS = 'GET_ALL_QUESTION_ANSWERS';
const UPDATE_QUESTION_ANSWER = 'UPDATE_QUESTION_ANSWER';

export {REGISTER_NEW_STUDENT, GET_ALL_QUESTION_ANSWERS, UPDATE_QUESTION_ANSWER};
